/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-04-30 10:13:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<header id=\"ban\">\r\n");
      out.write("</header>\r\n");
      out.write("<nav>\r\n");
      out.write("\t<ul id=\"menu\">\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<a href=\"index\">Accueil</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<a href=\"#\">Integrale</a>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Comité</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">PES</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">BDA</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">BCS</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">PET</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<a href=\"#\">TEA</a>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"tea\">Mes TEA</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"annonces\">Annonces</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"deposerannonce\">Déposer une annonce</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<aside>\r\n");
      out.write("\t<h2>Mon profil</h2>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li>Martin Deligny</li>\r\n");
      out.write("\t\t<li>Profil : etudiant</li>\r\n");
      out.write("\t\t<li>Matricule : 11105</li>\r\n");
      out.write("\t\t<li>Promotion 2015</li>\r\n");
      out.write("\t\t<li>TEA restantes : 0h</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li class=\"menu\"><a href=\"administration\">Panneau d'administration</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li class=\"menu\"><a href=\"validationannonces\">Annonces en attente</a></li>\r\n");
      out.write("\t\t<li class=\"menu\"><a href=\"gestiontea\">Gestion des TEA</a></li>\r\n");
      out.write("\t\t<li class=\"menu\"><a href=\"#\">Se déconnecter</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</aside>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
